site_name: 精英计划，入门指北
theme:
  name: material
  language: zh
  logo: assets/jyjhie.jpg
  favicon: assets/jyjhie.jpg
  icon:
    repo: fontawesome/brands/github
  custom_dir: overrides
  palette: 
    - primary: white
      accent: light blue
      toggle:
        icon: material/lightbulb-off-outline 
        name: Switch to dark mode
    - primary: black
      accent: light blue
      scheme: slate
      toggle:
        icon: material/lightbulb
        name: Switch to light mode
  features:
    - header.autohide
    # - navigation.instant
    # - navigation.expand
    # - navigation.sections
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    - content.code.annotate

edit_uri: edit/main/docs/
repo_url: https://github.com/jyjhie/readme
repo_name: jyjhie/readme
extra:
  homepage: https://readme.jyjh.club
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jyjhie/readme
copyright: <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/"><img alt="Creative Commons License" style="border-width:0" src="https://readme.jyjh.club/assets/by-nc-sa.png" /></a><br />This work is licensed under a <a rel="license" href="http://creativecommons.org/licenses/by-nc-sa/4.0/">Creative Commons Attribution-NonCommercial-ShareAlike 4.0 International License</a>.
markdown_extensions:
  - admonition              # 提示块
  - footnotes               # 脚注
  - meta                    # 定义元数据，通过文章上下文控制，如disqus
  - pymdownx.caret          # 下划线上标
  - pymdownx.tilde          # 删除线下标
  - pymdownx.critic         # 增加删除修改高亮注释，可修饰行内或段落
  - pymdownx.details        # 提示块可折叠
  - pymdownx.inlinehilite   # 行内代码高亮
  - pymdownx.mark           # 文本高亮
  - pymdownx.smartsymbols   # 符号转换
  - pymdownx.superfences    # 代码嵌套在列表里
  - codehilite:             # 代码高亮，显示行号
      guess_lang: true
      linenums: true
  - toc:                    # 锚点
      permalink: true
  - pymdownx.arithmatex:    # 数学公式
      generic: true
  - pymdownx.betterem:      # 对加粗和斜体更好的检测
      smart_enable: all
  - pymdownx.magiclink      # 自动识别超链接
  - pymdownx.tasklist:      # 复选框checklist
      custom_checkbox: true
extra_javascript:
  - mathjax/config.js
  - mathjax/tex-mml-chtml.js

plugins:
  - git-revision-date-localized
  - minify:
      minify_html: true

nav:
  - 前言: index.md
  - 升学or就业:
    - 考研:
      - 关于考研: 升学or就业/考研/README.md
    - 保研:
      - 关于保研: 升学or就业/保研/README.md
    - 出国:
      - 关于出国: 升学or就业/出国/README.md
    - 工作:
      - 关于工作: 升学or就业/工作/README.md
    - 考公:
      - 关于考公: 升学or就业/考公/README.md
  - 公共课:
    - 高数: 公共课/高数.md
    - 线代: 公共课/线代.md
    - C语言程序设计: 公共课/C语言程序设计.md
    - 电路分析: 公共课/电路分析.md
    - 数理逻辑: 公共课/数理逻辑.md
    - 概率论与数理统计: 公共课/概率论与数理统计.md
    - 英语: 公共课/英语.md
    - 数字逻辑电路: 公共课/数字逻辑电路.md
    - 马原: 公共课/马原.md
    - 毛中特: 公共课/毛中特.md
  - 计科:
    - 大二上:
      - 汇编语言程序设计: 计科/大二上/汇编语言程序设计.md
      - 数据结构与算法: 计科/大二上/数据结构与算法.md
      - 图论: 计科/大二上/图论.md
    - 大二下:
      - 计算机组成原理: 计科/大二下/计算机组成原理.md
      - 面向对象程序设计: 计科/大二下/面向对象程序设计.md
      - 计算机网络原理: 计科/大二下/计算机网络原理.md
    - 大三上:
      - 操作系统: 计科/大三上/操作系统.md
      - 数据库原理: 计科/大三上/数据库原理.md
      - 软件工程: 计科/大三上/软件工程.md
      - 网络工程: 计科/大三上/网络工程.md
      - 软件测试技术: 计科/大三上/软件测试技术.md
    - 大三下:
      - 编译原理: 计科/大三下/编译原理.md
      - 编译器设计与实践: 计科/大三下/编译器设计与实践.md
      - 智能信息获取技术: 计科/大三下/智能信息获取技术.md
  - 电子:
    - 大二上:
      - 大物: 电子/大二上/大物.md
      - 电磁: 电子/大二上/电磁.md
      - 模电: 电子/大二上/模电.md
      - 数电: 电子/大二上/数电.md
    - 大二下:
      - HDL: 电子/大二下/HDL.md
      - 信号与系统: 电子/大二下/信号与系统.md
      - 电子测量: 电子/大二下/电子测量.md
      - 网络基础: 电子/大二下/网络基础.md
      - 高频: 电子/大二下/高频.md
    - 大三上:
      - SOPC设计与实践: 电子/大三上/SOPC设计与实践.md
      - Python: 电子/大三上/Python.md
      - 单片机原理及接口技术: 电子/大三上/单片机原理及接口技术.md
      - 嵌入式系统: 电子/大三上/嵌入式系统.md
      - 数字图像处理: 电子/大三上/数字图像处理.md
      - 数字信号处理: 电子/大三上/数字信号处理.md
    - 大三下:
      - DSP: 电子/大三下/DSP.md
      - 通信原理: 电子/大三下/通信原理.md
  - 比赛:
    - 电赛: 比赛/电赛.md
    - 数学建模: 比赛/数学建模.md
    - 集成电路: 比赛/集成电路.md
    - 高数竞赛: 比赛/高数竞赛.md
    - 蓝桥杯: 比赛/蓝桥杯.md
    - ICPC: 比赛/ICPC.md
    - CCPC: 比赛/CCPC.md
